name: Linting and Tests CI

on:
  push:
    branches: [CI-Pipeline]

  pull_request:
    branches: [CI-Pipeline, Development]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13, 3.14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-asyncio httpx mypy black isort bandit pip-audit

      - name: Lint and Static Checks
        run: |
          echo "Running linting and static analysis checks"
          flake8 src --max-line-length=130 --exclude=__pycache__,.pytest_cache
          mypy src
          black --check src
          isort --check-only src
          bandit -r src
          pip-audit

      - name: Run Unit Tests
        run: |
          echo "Running backend unit tests"
          pytest src/tests/backend_test -v --disable-warnings --maxfail=1
