name: Linting CI

on:
  pull_request:
    branches: [Development]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-asyncio httpx

      - name: Lint code
        run: |
          echo "Running linting tests"
          flake8 src --max-line-length=130 --exclude=__pycache__,.pytest_cache

      - name: Run Unit Tests
        run: |
          echo "Running unit tests"
          pytest src/tests/backend -v --disable-warnings --maxfail=1
